// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "FRITZ!Box 7520 QB";    // Network SSID (name)
const char PASS[]     = "02100898750741008823";    // Network password (use for WPA, or use as key for WEP)


float led_current;
float motor_current;
float total_current;

void initProperties(){

  ArduinoCloud.addProperty(led_current, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(motor_current, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(total_current, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
